sudo: false
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools

    - build-tools-26.0.2
    - android-27
before_install:
# https://stackoverflow.com/a/47719835/1275092
- yes | sdkmanager "platforms;android-27"
script:
- ./gradlew check jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)